spring.main.web-application-type=none
spring.application.name=modulo-gerencia
spring.datasource.url=jdbc:sqlserver://127.0.0.1:1433;databaseName=MUTUALIDAD;encrypt=false
spring.datasource.username=sa
spring.datasource.password=123456.
spring.jpa.hibernate.ddl-auto=none